[package]
name = "telegram_bot"
version = "0.1.0"
authors = ["Maximilian Staab <maximilian.staab@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"