[package]
name = "trash_bot"
version = "0.1.0"
authors = ["Maximilian Staab <maximilian.staab@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
maplit = "1.0.2"
lazy_static = "1.4.0"
graphql_client = "0.9.0"
reqwest = { version = "0.11.3", features = ["json"] }
chrono-tz = "0.5.3"
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread"] }
anyhow = { version = "1.0.40" }
pretty_env_logger = "0.4.0"
teloxide = { version = "0.4.0", features = ["macros", "auto-send"] }
log = "0.4.14"
futures = "0.3.14"
